stages:
  - base
  # - modules
  - wheels
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: none

.docker-in-docker:
    retry:
        max: 2
        when:
            - always
    image: docker:stable
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    before_script:
        - apk --update add py3-pip openssh-client rsync git file bash python3 py3-cffi py3-cryptography
        - pip3 install -U docker jinja2 docopt twine
        - echo $DOCKER_PW | docker login --username="$DOCKER_USER" --password-stdin
        - git submodule update --init .ci/shared
    services:
        - docker:dind
    environment:
        name: unsafe
    # stage: modules
    script: .ci/shared/docker/update_test_dockers.py ${MODULE_NAME}

base:
    extends: .docker-in-docker
    stage: base
    variables:
      MODULE_NAME: BASE

# gdt:
#     extends: .docker-in-docker
#     variables:
#       MODULE_NAME: dune-gdt

# super:
#   extends: .docker-in-docker
#   variables:
#     BASE: debian
#     IMAGE: dunecommunity/gdt-super_${BASE}:${CI_COMMIT_SHA}
#   script: |
#     docker build --build-arg BASE=${BASE} -t ${IMAGE} -f .ci/shared/docker/super_docker/Dockerfile .
#     docker push ${IMAGE}

.wheels_base:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_USERNAME: gitlab-ci-token
    GITLAB_PYPI: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  stage: wheels
  needs: []
  extends: .docker-in-docker
  # try to download from gitlab first, then pypi
  before_script:
    - !reference [.docker-in-docker, before_script]
    - python3 -m pip config set global.index-url ${GITLAB_PYPI}
    - python3 -m pip config set global.extra-index-url https://pypi.org/simple
    - python3 -m pip config set global.trusted-host zivgitlab.uni-muenster.de
  script:
    - ./make_docker_wheels.bash
    - python3 -m twine check docker/wheelhouse/final/*.whl
  artifacts:
    paths:
      - docker/wheelhouse/final/*.whl
  cache:
    paths:
      - docker/cache

wheels 3.7:
  extends: .wheels_base
  variables:
    GDT_PYTHON_VERSION: "3.7"
  cache:
    key: $CI_COMMIT_REF_SLUG_3.7

wheels 3.8:
  extends: .wheels_base
  variables:
    GDT_PYTHON_VERSION: "3.8"
  cache:
    key: $CI_COMMIT_REF_SLUG_3.8

wheels 3.9:
  extends: .wheels_base
  variables:
    GDT_PYTHON_VERSION: "3.9"
  cache:
    key: $CI_COMMIT_REF_SLUG_3.9

.publish:
  image: alpine:3.15
  dependencies: ["wheels 3.9", "wheels 3.8", "wheels 3.7"]
  needs: ["wheels 3.9", "wheels 3.8", "wheels 3.7"]
  stage: publish
  before_script:
      - apk --update add py3-pip git file bash python3 py3-cffi py3-cryptography
      - pip3 install -U twine
  variables:
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_USERNAME: gitlab-ci-token
  script:
    -  python3 -m twine upload --repository-url ${GITLAB_PYPI} ${MOD_WHEEL}
  artifacts:
    paths:
      - ${MOD_WHEEL}
    
publish dune-xt:
  extends: .publish
  variables:
    MOD_WHEEL: docker/wheelhouse/final/dune_xt*.whl

publish dune-gdt:
  extends: .publish
  variables:
    MOD_WHEEL: docker/wheelhouse/final/dune_xt*.whl