stages:
  - base
  # - modules
  - wheels
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: none

.docker-in-docker:
    retry:
        max: 2
        when:
            - always
    image: docker:stable
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    before_script:
        - apk --update add py3-pip openssh-client rsync git file bash python3 py3-cffi py3-cryptography
        - pip3 install -U docker jinja2 docopt twine
        - echo $DOCKER_PW | docker login --username="$DOCKER_USER" --password-stdin
        - git submodule update --init .ci/shared
    services:
        - docker:dind
    environment:
        name: unsafe
    # stage: modules
    script: .ci/shared/docker/update_test_dockers.py ${MODULE_NAME}

base:
    extends: .docker-in-docker
    stage: base
    variables:
      MODULE_NAME: BASE

# gdt:
#     extends: .docker-in-docker
#     variables:
#       MODULE_NAME: dune-gdt

# super:
#   extends: .docker-in-docker
#   variables:
#     BASE: debian
#     IMAGE: dunecommunity/gdt-super_${BASE}:${CI_COMMIT_SHA}
#   script: |
#     docker build --build-arg BASE=${BASE} -t ${IMAGE} -f .ci/shared/docker/super_docker/Dockerfile .
#     docker push ${IMAGE}

.wheels_base:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_USERNAME: gitlab-ci-token
  stage: wheels
  needs: []
  extends: .docker-in-docker
  script:
    - ./make_docker_wheels.bash
    - python3 -m twine check docker/wheelhouse/final/*.whl
  artifacts:
    paths:
      - docker/wheelhouse/final/*.whl

wheels 3.7:
  extends: .wheels_base
  variables:
    GDT_PYTHON_VERSION: "3.7"

wheels 3.8:
  extends: .wheels_base
  variables:
    GDT_PYTHON_VERSION: "3.8"

wheels 3.9:
  extends: .wheels_base
  variables:
    GDT_PYTHON_VERSION: "3.9"

publish:
  image: alpine:3.12
  dependencies: ["wheels 3.9", "wheels 3.8", "wheels 3.7"]
  stage: publish
  before_script:
      - apk --update add py3-pip git file bash python3 py3-cffi py3-cryptography
      - pip3 install -U twine
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python3 -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi docker/wheelhouse/final/*.whl
  artifacts:
    paths:
      - docker/wheelhouse/final/*.whl
